### ISSUE TITLE
Week 0 review: Teams and Jobs

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/Data-Structures#1]
Scrum Team GitHub pages (2 points)

- Web Project: Project Description, Project Plans/Ideas/Wires, Time box 
- Team Roles described, Project Owner or Sponsor described, Scrum Board started

[Most info in readme](https://github.com/parkjessie/LAJ#readme), no wireframes, [scrum board](https://github.com/parkjessie/LAJ/projects/1)

Individual GitHub pages (3 points)

- GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions [here](https://xiaoa0.github.io/Data-Structures/notes/week0)
- GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime [here](https://xiaoa0.github.io/Data-Structures/)
- GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime [here](https://xiaoa0.github.io/Data-Structures/create-task)

**Comment by MaBoinjd** [comment]
# Total Score - 4.5/5

# Scrum team
There were no visuals for the wireframe of the project and scrum board only had one ticket so maybe start adding more to the scrum board. 1.5/2

# Individual parts 
Had all notes with actions, showed github code and replit, and had a link to runtime as a create task (along with writeups from last trimester). 3/3
