### ISSUE TITLE
Week 1: Lists and Loops

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/Data-Structures#2]
Individual GitHub pages (3 points)
[GitHub page](https://xiaoa0.github.io/Data-Structures/notes/week1) for Test Prep study, requiring 5.3, 5.4 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/)).
- [x] One Check 5.3
- [x] One Check 5.4
GitHub page that documents key learnings and code snippets using GitHub and [replit](https://replit.com/@axiao05/tt-assignments#lists.py).

InfoDB lists
- [x] One Check for New Data, minimum of 4 items

InfoDB loops
- [x] One Check For Loop running and sensible output
- [x] One Check While Loop running and sensible output
- [x] One Check Recursion running and sensible output

Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
- [ ] Algorithm 
- [ ] Comments
- [ ] Prints result
- [ ] Prints Complete List

- [ ] Comments and documentation throughout

INDIVIDUAL to send (Indi score: Checks/11 = score/3) + Team Score
Two DMs for Mortensen, Team Channel for Naidu
Review ticket with total score, include teams score from Friday (n/5) and name of grader next to score.
GitHub pages

**Comment by MaBoinjd** [comment]
Name of grader: Erik Peterson
Total score: (6/11) + 1.9/2 = 3.5/5

Github Page: +2, has TPT notes and actions

Replit:
InfoDB Lists
+1, has 4 items
InfoDB Loops
+1, has for loop working
+1, has while loop working
+1, has recursive loop working

No Fibonacci
Has no algorithm, comments, prints results, prints complete list for fibonacci

No comments or documentatio in replit.
