### ISSUE TITLE
Week 2: Classy Functions

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/Data-Structures#4]
Total score: 2.5/5, graded by Erik Peterson

Team scoring: 2/2 
[Week 2 Review Ticket](https://github.com/parkjessie/LAJ/issues/10)

Individual scoring: 
[TPT notes](https://xiaoa0.github.io/Data-Structures/notes/week2)
[Repl](https://replit.com/@axiao05/tt-assignments)

**Comment by kkwan0** [comment]
Team Score: 2/2, all requirements were met, and all questions were answered

**Comment by MaBoinjd** [comment]
Individual Score: 0.5/3 + Team Score: 2/2 = Total Score: 2.5/5
Graded by Erik Peterson

Has 5.5 and 5.6 notes. 
Semi-organized files.
Repl is uncompleted with attempts at factorial and math functions. (0.5/3) for attempts
No attempt at palindrome.

(0.5/3) for attempts and notes.
