### ISSUE TITLE
Week 4: Accounts and Logins

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/Data-Structures#6]
### Score: /5

**Create Task:** 
- CB Create Task Coding requirements documented on [Github Pages](https://xiaoa0.github.io/Data-Structures/pages/create-task), [Wiki](https://github.com/xiaoa0/Data-Structures/wiki/Create-Task-documentation)
- [Runtime](https://replit.com/@axiao05/hangman#main.py) of Code(with comments) on Replit/IntelliJ

**Accounts and Logins Challenges/Hacks**

- Analysis/reflection on [Github Pages](https://xiaoa0.github.io/Data-Structures/pages/notes/tt3) and [Wiki](https://github.com/xiaoa0/Data-Structures/wiki/TT3-Accounts-and-Login)
- Hack 1: Add Phone Number to Sign Up / Authorization screen
- Hack 2: Add logout to CRUD screen
- Hack 3: Add login_required to another portion of the project
- Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by David-Xie123** [comment]
4/5, because everything is there except for Hack 2 (the logout to the CRUD screen)
