### ISSUE TITLE
Week 5: AP Prep

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/Data-Structures#8]
**Score: 5/5**

[Github Pages](https://xiaoa0.github.io/Data-Structures/)

- Review ticket with [study plan](https://github.com/xiaoa0/Data-Structures/issues/7) for week
- [Corrections](https://xiaoa0.github.io/Data-Structures/github_pages/ap-prep) and scores for both MCQs
- Create Task feedback from Mr. Mortensen is recorded on study plan
- Crossover grading done by Jay
- Jay asked to be reviewed by Karthik

**Comment by JayManjrekar** [comment]
**Score 5/5**
Allie has a study plan, linked on another github page with the tangibles linked taking me to her github page. She has both of her MCQ scores and corrections linked as well with high scores on both. For her create task she is in progress and has gotten it checked by Mr. Mortensen.
